name: Python - Lint and Test
on: 
  push:
    paths:
      - 'thymedrift/**'
      - 'tests/**'
      - 'requirements.txt'
      - 'requirements.azure.txt'
      - '.github/workflows/python.yml'
  pull_request:
    paths:
      - 'thymedrift/**'
      - 'tests/**'
      - 'requirements.txt'
      - 'requirements.azure.txt'
      - '.github/workflows/python.yml'

jobs:
  lint:
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      # Setup Python
      - name: Setup Python ${{ matrix.python-version }}
        id: python_setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Checkout repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v2
      
      # Run Python Linting
      - name: Run Python Linting
        id: python_linting
        run: |
          python -m pip install --upgrade pip
          pip install flake8 -q
          flake8 app/ --count --ignore=E501,F401 --show-source --statistics
          flake8 tests/ --count --ignore=F401,E501,E402,E712 --show-source --statistics
      
      # Run Python Tests
      - name: Run Python Tests
        id: python_test
        run: |
          pip install pytest -q
          pip install -r requirements.txt -q
          pip install -r requirements.azure.txt -q
          python -m spacy download en_core_web_trf
          python -m pytest